### ISSUE TITLE
frame-src error from recent changes

### ISSUE THREAD

**Issue by marcolarosa** [Sciebo-RDS/oc-describo#10]
<img width="1718" alt="Screen Shot 2021-07-27 at 6 00 05 pm" src="https://user-images.githubusercontent.com/2639995/127118422-c3d589b5-0246-4092-b29f-aa59b75272ca.png">

Describo doesn't load into the frame on main latest commit!

**Comment by Heiss** [comment]
Jep, there was an error in the key of second getAppValue. *Dough* But now it is fixed. :)
