### ISSUE TITLE
things needs to be done

### ISSUE THREAD

**Issue by Heiss** [Sciebo-RDS/oc-describo#2]
see comments

**Comment by marcolarosa** [comment]
Connecting owncloud to describo so that owncloud can create a new describo session
* [x] describo config needs an application defined in the configuration like:
   * the name can be anything but for now make it the origin of whatever is doing the POST
   * the secret can be anything at all
   * don't worry about postCrate to for now
```
    "api": {
        "port": 8080,
        "applications": [
            {
                "name": "localhost:8000",
                "secret": "secret-key-shared-with-owncloud",
                "postCrateTo": {
                    "url": "http://localhost:8080/save",
                    "headers": { "Authorization": "Bearer yyy", "Content-Type": "application/json" }
                }
            }
        ]
    }
```

* [x] owncloud configuration needs to be able to set secret key as defined in describo config
* [x] owncloud does POST to describo /api/session/application with header and this secret

**Comment by marcolarosa** [comment]
* [x] nice to have - please extract config into separate configuration.php
   * [x] app still has settings page
   * [x] on load it looks for configuration.php and fails if not found
   * [x] if found loads from that file: apiURL (was cloudURL), uiURL, oauthname, describoSecretKey
      * [x] documentation in configuration.php for apiURL - this is the internal network name

**Comment by marcolarosa** [comment]
Docker compose brilliant. Please change DB host to something other than db as it clashes with the name in describo's docker-compose:

```
    owncloud_db:
        image: webhippie/mariadb:latest
        restart: always
        ....
```

**Comment by marcolarosa** [comment]
Fix PageController: 

```
diff --git a/php/lib/Controller/PageController.php b/php/lib/Controller/PageController.php
index 30b1a81..e3bac53 100644
--- a/php/lib/Controller/PageController.php
+++ b/php/lib/Controller/PageController.php
@@ -101,7 +101,7 @@ class PageController extends Controller

     private function describoSession()
     {
-        $url = $this->config->getAppValue($this->appName, "cloudURL", "http://ui:9000") . "/api/session/application";
+        $url = $this->config->getAppValue($this->appName, "cloudURL", "http://ui:9000");
         $client = $this->clientMapper->findByName($this->config->getAppValue($this->appName, "oauthname", "describo"));

         $user = \OC::$server->getUserSession()->getUser();
@@ -132,7 +132,7 @@ class PageController extends Controller
         curl_setopt($ch, CURLOPT_POST, 1);
         $headers = array(
             'Content-Type: application/json',
-            'Authorization: Bearer: ' .  $client->getSecret()
+            'Authorization: Bearer ' .  $client->getSecret()
         );
         curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
         curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);

```
