### ISSUE TITLE
Incorrect URL for iframe

### ISSUE THREAD

**Issue by marcolarosa** [Sciebo-RDS/oc-describo#3]
Here's the diff:
```
+++ b/php/lib/Controller/PageController.php

-        $iframeUrl .= "?sid=" . $this->describoSession();
+        $iframeUrl .= "/application?sid=" . $this->describoSession();
```

The URL is `/application?sid=...`. And then, you won't see a login box. You'll actually be logged in! :)

**Comment by Heiss** [comment]
This should be done in `configuration.php`, so it is the default value for the iframe url. No need to make a fixed string concat. :)
