### ISSUE TITLE
Passing data to describo to set up a session

### ISSUE THREAD

**Issue by marcolarosa** [Sciebo-RDS/oc-describo#9]
Documentation: 
* https://github.com/Arkisto-Platform/describo-online/wiki/Integrating-Describo-Online-into-another-service
* https://github.com/Arkisto-Platform/describo-online/wiki/Integrating-Describo-Online-into-owncloud

The data required to setup a session is as:
https://github.com/Sciebo-RDS/oc-describo/blob/main/php/lib/Controller/PageController.php#L132-L138

You can add another parameter there `folder` which is the path of the folder to load relative to the users home directory.

So, if my username is admin and I have a folder `crate` in my home directory the value to put in is `/crate` (note: not the full webdav path)

**Comment by Heiss** [comment]
works fine in sciebo RDS
